(()=>{
'use strict';
const CAL_POINTS=[
 [.10,.12],[.37,.12],[.63,.12],[.90,.12],
 [.10,.38],[.37,.38],[.63,.38],[.90,.38],
 [.10,.64],[.37,.64],[.63,.64],[.90,.64],
 [.10,.88],[.37,.88],[.63,.88],[.90,.88]
];
const VERIFY_POINTS=[
 [.14,.16],[.50,.16],[.86,.16],
 [.14,.50],[.50,.50],[.86,.50],
 [.14,.84],[.50,.84],[.86,.84]
];
const IDS={lIris:[468,469,470,471,472],rIris:[473,474,475,476,477],lCorners:[33,133],rCorners:[362,263],lTop:[159,160],lBottom:[145,144],rTop:[386,385],rBottom:[374,380]};
const gid=id=>document.getElementById(id),gc=(v,a,b)=>Math.max(a,Math.min(b,v));
const median=a=>{if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y);return b[(b.length-1)>>1]};
const avg=(raw,ids)=>{let x=0,y=0,z=0,n=0;for(const id of ids){const p=raw?.[id];if(!p)continue;x+=p.x;y+=p.y;z+=p.z||0;n++}return n?{x:x/n,y:y/n,z:z/n}:null};
let stream=null,raf=0,busy=false,lastDetect=0,mode='idle',inferMax=960,perfSamples=[];
let calIndex=0,phaseStarted=0,pointSamples=[],calSamples=[],headAnchor=null,headRef={yaw:0,pitch:0};
let verifyIndex=0,verifySamples=[],verifyResults=[],model=null,flipOutputX=false,corrModel=null;
let smoothed=null,predHistory=[],rawLast=null,featureLast=null,missSince=0,lastLightCheck=0,lightLevel=100,contrastLevel=30;
let targets=[],particles=[],score=0,lastSpawn=0,gameLast=0;
function eyeGeom(raw,corners,tops,bottoms,irisIds){
 const iris=avg(raw,irisIds),a=raw?.[corners[0]],b=raw?.[corners[1]],top=avg(raw,tops),bottom=avg(raw,bottoms);if(!iris||!a||!b||!top||!bottom)return null;
 const minX=Math.min(a.x,b.x),maxX=Math.max(a.x,b.x),w=Math.max(1e-5,maxX-minX),minY=Math.min(top.y,bottom.y),maxY=Math.max(top.y,bottom.y),h=Math.max(1e-5,maxY-minY),cornerW=Math.max(1e-5,Math.hypot(a.x-b.x,a.y-b.y)),open=Math.hypot(top.x-bottom.x,top.y-bottom.y)/cornerW;
 return{h:(iris.x-minX)/w,v:(iris.y-minY)/h,open,iris}
}
function features(raw){
 if(!raw||raw.length<478)return null;const L=eyeGeom(raw,IDS.lCorners,IDS.lTop,IDS.lBottom,IDS.lIris),R=eyeGeom(raw,IDS.rCorners,IDS.rTop,IDS.rBottom,IDS.rIris);if(!L||!R)return null;
 const le=raw[234],re=raw[454],n=raw[1],f=raw[10],c=raw[152];if(!le||!re||!n||!f||!c)return null;const fw=Math.max(1e-5,Math.hypot(re.x-le.x,re.y-le.y)),yaw=(n.x-(le.x+re.x)/2)/fw,pitch=(n.y-f.y)/Math.max(1e-5,c.y-f.y);
 return{lh:L.h,lv:L.v,rh:R.h,rv:R.v,h:(L.h+R.h)/2,v:(L.v+R.v)/2,dh:L.h-R.h,dv:L.v-R.v,yaw,pitch,l:L.iris,r:R.iris,openL:L.open,openR:R.open,faceWidth:Math.abs(re.x-le.x)}
}
function basis(f,ref=headRef){const y=f.yaw-ref.yaw,p=f.pitch-ref.pitch;return[1,f.lh,f.lv,f.rh,f.rv,f.h,f.v,f.dh,f.dv,f.h*f.v,f.lh*f.lv,f.rh*f.rv,f.h*f.h,f.v*f.v,y,p,y*f.h,p*f.v]}
function solve(A,b){const n=b.length,M=A.map((r,i)=>r.slice().concat(b[i]));for(let i=0;i<n;i++){let p=i;for(let r=i+1;r<n;r++)if(Math.abs(M[r][i])>Math.abs(M[p][i]))p=r;if(Math.abs(M[p][i])<1e-10)return null;[M[i],M[p]]=[M[p],M[i]];const d=M[i][i];for(let c=i;c<=n;c++)M[i][c]/=d;for(let r=0;r<n;r++){if(r===i)continue;const k=M[r][i];if(!k)continue;for(let c=i;c<=n;c++)M[r][c]-=k*M[i][c]}}return M.map(r=>r[n])}
function fitAxis(samples,key,ref=headRef,lambda=.028){const n=18,A=Array.from({length:n},()=>Array(n).fill(0)),b=Array(n).fill(0);for(const s of samples){const x=basis(s.f,ref),y=s[key];for(let i=0;i<n;i++){b[i]+=x[i]*y;for(let j=0;j<n;j++)A[i][j]+=x[i]*x[j]}}for(let i=1;i<n;i++)A[i][i]+=lambda;return solve(A,b)}
const dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0);
function percentile(a,p){if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),i=Math.min(b.length-1,Math.max(0,Math.floor((b.length-1)*p)));return b[i]}
function fitModel(){
 if(calSamples.length<90)throw Error('보정 데이터가 부족합니다.');headRef={yaw:median(calSamples.map(s=>s.f.yaw)),pitch:median(calSamples.map(s=>s.f.pitch))};
 let bx=fitAxis(calSamples,'x'),by=fitAxis(calSamples,'y');if(!bx||!by)throw Error('시선 보정식을 계산하지 못했습니다.');
 const errs=calSamples.map(s=>Math.hypot(dot(bx,basis(s.f))-s.x,dot(by,basis(s.f))-s.y)),cut=Math.max(.055,percentile(errs,.86));const good=calSamples.filter((s,i)=>errs[i]<=cut);
 if(good.length>=75){const x2=fitAxis(good,'x'),y2=fitAxis(good,'y');if(x2&&y2){bx=x2;by=y2}}
 let err=0;for(const s of good)err+=Math.hypot(dot(bx,basis(s.f))-s.x,dot(by,basis(s.f))-s.y);model={bx,by,trainError:err/Math.max(1,good.length)};return model
}
function predictRaw(f){if(!model||!f)return null;return{x:gc(dot(model.bx,basis(f)),0,1),y:gc(dot(model.by,basis(f)),0,1)}}
function corrBasis(p){return[1,p.x,p.y,p.x*p.y,p.x*p.x,p.y*p.y]}
function fitCorrection(rows,key){const n=6,A=Array.from({length:n},()=>Array(n).fill(0)),b=Array(n).fill(0);for(const r of rows){const x=corrBasis(r.p),y=r[key];for(let i=0;i<n;i++){b[i]+=x[i]*y;for(let j=0;j<n;j++)A[i][j]+=x[i]*x[j]}}for(let i=1;i<n;i++)A[i][i]+=.08;return solve(A,b)}
function applyOrientation(p){return{x:flipOutputX?1-p.x:p.x,y:p.y}}
function applyCorrection(p){if(!corrModel)return p;const cb=corrBasis(p),dx=gc(dot(corrModel.cx,cb),-.14,.14),dy=gc(dot(corrModel.cy,cb),-.14,.14);return{x:gc(p.x+dx,0,1),y:gc(p.y+dy,0,1)}}
function predict(f){let p=predictRaw(f);if(!p)return null;p=applyCorrection(applyOrientation(p));predHistory.push(p);if(predHistory.length>5)predHistory.shift();const med={x:median(predHistory.map(v=>v.x)),y:median(predHistory.map(v=>v.y))};if(!smoothed){smoothed=med;return med}const d=Math.hypot(med.x-smoothed.x,med.y-smoothed.y),alpha=gc(.14+d*2.1,.14,.58);smoothed={x:smoothed.x*(1-alpha)+med.x*alpha,y:smoothed.y*(1-alpha)+med.y*alpha};return smoothed}
function status(s){const a=gid('gazeStatus'),b=gid('calStatus');if(a)a.textContent=s;if(b)b.textContent=s}
function gameHint(s){const e=document.querySelector('#gazeGame .gameHint');if(e)e.textContent=s}
function resizeCanvas(){const c=gid('gazeCanvas');if(!c)return;const r=c.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1),w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(c.width!==w||c.height!==h){c.width=w;c.height=h}}
function mapVideoPoint(p){const v=gid('gazeVideo'),c=gid('gazeCanvas');if(!p||!v||!c||!v.videoWidth||!v.videoHeight)return null;const cw=c.width,ch=c.height,sw=v.videoWidth,sh=v.videoHeight,k=Math.max(cw/sw,ch/sh),rw=sw*k,rh=sh*k,ox=(cw-rw)/2,oy=(ch-rh)/2;return{x:cw-(ox+p.x*sw*k),y:oy+p.y*sh*k}}
function attachStage(game){const v=gid('gazeVideo'),c=gid('gazeCanvas'),host=game?document.querySelector('#gazeGame .gameStage'):document.querySelector('#gazeCal .gazeStage');if(!v||!c||!host)return;host.insertBefore(v,host.firstChild);host.insertBefore(c,v.nextSibling)}
function stop(){cancelAnimationFrame(raf);raf=0;busy=false;mode='idle';if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}const v=gid('gazeVideo');if(v)v.srcObject=null}
async function start(){stop();attachStage(false);mode='loading';show('gazeCal');status('카메라 준비 중…');if(!navigator.mediaDevices?.getUserMedia)throw Error('카메라 접근이 제한되어 있습니다. Chrome에서 열어주세요.');const mp=loadTask();stream=await openCamera();const v=gid('gazeVideo');v.srcObject=stream;await v.play();status('홍채 모델 준비 중…');await mp;calIndex=0;pointSamples=[];calSamples=[];verifyIndex=0;verifySamples=[];verifyResults=[];model=null;corrModel=null;flipOutputX=false;smoothed=null;predHistory=[];headAnchor=null;missSince=0;inferMax=960;perfSamples=[];const d=gid('calDot');if(d)d.style.display='block';mode='cal';prepareCal();lastDetect=0;raf=requestAnimationFrame(loop)}
function prepareCal(){const p=CAL_POINTS[calIndex],d=gid('calDot'),prog=gid('calProgress');if(!p||!d)return;d.style.display='block';d.style.left=p[0]*100+'%';d.style.top=p[1]*100+'%';d.classList.remove('capture');void d.offsetWidth;d.classList.add('capture');if(prog)prog.textContent=`보정 ${calIndex+1} / ${CAL_POINTS.length}`;phaseStarted=performance.now();pointSamples=[]}
function prepareVerify(){const p=VERIFY_POINTS[verifyIndex],d=gid('calDot'),prog=gid('calProgress');if(!p||!d)return;d.style.display='block';d.style.left=p[0]*100+'%';d.style.top=p[1]*100+'%';d.classList.remove('capture');void d.offsetWidth;d.classList.add('capture');if(prog)prog.textContent=`정확도 확인 ${verifyIndex+1} / ${VERIFY_POINTS.length}`;phaseStarted=performance.now();verifySamples=[]}
function envMessage(f){if(lightLevel<46)return'환경이 너무 어두워요. 얼굴 앞쪽이 밝은 곳으로 이동해 주세요.';if(contrastLevel<13)return'얼굴이 흐리게 보여요. 더 밝은 곳에서 카메라를 닦고 다시 맞춰 주세요.';if(lightLevel<66)return'조금 어두워요. 얼굴 앞쪽을 밝게 하면 정확도가 좋아집니다.';if(f?.faceWidth<.23)return'얼굴이 조금 멀어요. 휴대폰을 조금 더 가까이 해주세요.';if(f?.faceWidth>.72)return'얼굴이 너무 가까워요. 휴대폰을 조금 멀리 해주세요.';if(f&&Math.min(f.openL,f.openR)<.105)return'눈을 자연스럽게 뜨고 점을 바라봐 주세요.';return null}
function headStable(f){if(!headAnchor){headAnchor={yaw:f.yaw,pitch:f.pitch};return true}return Math.abs(f.yaw-headAnchor.yaw)<.105&&Math.abs(f.pitch-headAnchor.pitch)<.09}
function robustPointFrames(frames){if(frames.length<6)return[];const mh=median(frames.map(f=>f.h)),mv=median(frames.map(f=>f.v)),my=median(frames.map(f=>f.yaw)),mp=median(frames.map(f=>f.pitch));return frames.filter(f=>Math.abs(f.yaw-my)<.045&&Math.abs(f.pitch-mp)<.04&&Math.abs(f.h-mh)<.12&&Math.abs(f.v-mv)<.16&&Math.min(f.openL,f.openR)>.105).slice(-12)}
function updateCal(now){if(mode!=='cal'||!featureLast)return;const env=envMessage(featureLast);if(env){status(env);return}if(!headStable(featureLast)){status('고개가 움직였어요. 휴대폰과 고개를 보정 시작 위치로 맞춰 주세요.');return}const age=now-phaseStarted;if(age<340){status('점만 눈으로 따라보세요 · 고개는 고정');return}if(age<1030){pointSamples.push({...featureLast});status('측정 중… 눈동자만 움직여 주세요');return}const good=robustPointFrames(pointSamples);if(good.length<6){phaseStarted=now-340;pointSamples=[];status('측정이 흔들렸어요. 같은 점을 다시 바라봐 주세요.');return}const t=CAL_POINTS[calIndex];for(const f of good)calSamples.push({f,x:t[0],y:t[1]});calIndex++;if(calIndex>=CAL_POINTS.length){try{fitModel();mode='verify';verifyIndex=0;prepareVerify()}catch(e){status(e.message);calIndex=0;calSamples=[];prepareCal()}return}prepareCal()}
function updateVerify(now){if(mode!=='verify'||!featureLast)return;const env=envMessage(featureLast);if(env){status(env);return}if(!headStable(featureLast)){status('정확도 확인 중입니다. 고개를 보정 시작 위치로 맞춰 주세요.');return}const age=now-phaseStarted;if(age<300){status('정확도 확인 중 · 점만 바라보세요');return}if(age<900){verifySamples.push({...featureLast});status('검증 측정 중…');return}const good=robustPointFrames(verifySamples);if(good.length<5){phaseStarted=now-300;verifySamples=[];return}const t=VERIFY_POINTS[verifyIndex],preds=good.map(predictRaw).filter(Boolean),p={x:median(preds.map(v=>v.x)),y:median(preds.map(v=>v.y))};verifyResults.push({target:t,p});verifyIndex++;if(verifyIndex<VERIFY_POINTS.length){prepareVerify();return}finishVerify()}
function correlation(rows,flip=false){const xs=rows.map(r=>flip?1-r.p.x:r.p.x),ys=rows.map(r=>r.target[0]),mx=xs.reduce((a,b)=>a+b,0)/xs.length,my=ys.reduce((a,b)=>a+b,0)/ys.length;let num=0,dx=0,dy=0;for(let i=0;i<xs.length;i++){const a=xs[i]-mx,b=ys[i]-my;num+=a*b;dx+=a*a;dy+=b*b}return num/Math.sqrt(Math.max(1e-9,dx*dy))}
function finishVerify(){let en=0,ef=0;for(const r of verifyResults){en+=Math.hypot(r.p.x-r.target[0],r.p.y-r.target[1]);ef+=Math.hypot((1-r.p.x)-r.target[0],r.p.y-r.target[1])}en/=verifyResults.length;ef/=verifyResults.length;const cn=correlation(verifyResults,false),cf=correlation(verifyResults,true);flipOutputX=(cf>cn+.10)||(ef+.025<en);const rows=verifyResults.map(r=>{const p=applyOrientation(r.p);return{p,dx:r.target[0]-p.x,dy:r.target[1]-p.y}}),cx=fitCorrection(rows,'dx'),cy=fitCorrection(rows,'dy');corrModel=cx&&cy?{cx,cy}:null;const pct=Math.round(Math.min(en,ef)*100),d=gid('calDot');if(d)d.style.display='none';if(Math.min(en,ef)>.18)status(`보정 정확도가 낮아요 · 검증 오차 약 ${pct}% · 밝은 곳에서 다시 보정하면 더 정확합니다.`);else status(`보정 완료 · 검증 오차 약 ${pct}%${flipOutputX?' · 좌우 방향 자동 보정':''} · 화면 구역 보정 적용`);mode='game';score=0;targets=[];particles=[];lastSpawn=0;gameLast=performance.now();smoothed=null;predHistory=[];const s=gid('gazeScore');if(s)s.textContent='0';attachStage(true);show('gazeGame');gameHint('물체를 잠시 바라보면 레이저로 깨집니다');setTimeout(resizeCanvas,0)}
function sampleLight(inf,now){if(now-lastLightCheck<650)return;lastLightCheck=now;try{const ctx=inf.getContext('2d',{willReadFrequently:true}),w=inf.width,h=inf.height,step=Math.max(5,Math.floor(Math.min(w,h)/26)),data=ctx.getImageData(0,0,w,h).data;let sum=0,sum2=0,n=0;for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){const i=(y*w+x)*4,l=data[i]*.2126+data[i+1]*.7152+data[i+2]*.0722;sum+=l;sum2+=l*l;n++}if(n){lightLevel=sum/n;contrastLevel=Math.sqrt(Math.max(0,sum2/n-lightLevel*lightLevel))}}catch{}}
function spawn(now){const c=gid('gazeCanvas');if(!c||targets.length>=6||now-lastSpawn<850)return;lastSpawn=now;const m=.11,x=m+Math.random()*(1-m*2),y=.18+Math.random()*.68,r=.045+Math.random()*.025;targets.push({x,y,r,heat:0,crack:0,seed:Math.random()*9999})}
function shatter(t){score+=100;const s=gid('gazeScore');if(s)s.textContent=String(score);for(let i=0;i<18;i++){const a=Math.random()*Math.PI*2,sp=.18+Math.random()*.38;particles.push({x:t.x,y:t.y,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp-.08,life:1,rot:Math.random()*6})}}
function updateGame(pred,dt,now){spawn(now);let hit=null;if(pred)for(const t of targets){if(Math.hypot(pred.x-t.x,pred.y-t.y)<t.r*1.12){hit=t;break}}for(const t of targets){if(t===hit){t.heat+=dt;t.crack=gc(t.heat/560,0,1)}else t.heat=Math.max(0,t.heat-dt*.36)}const dead=targets.filter(t=>t.heat>=560);for(const t of dead)shatter(t);targets=targets.filter(t=>t.heat<560);for(const p of particles){p.x+=p.vx*dt/1000;p.y+=p.vy*dt/1000;p.vy+=.32*dt/1000;p.life-=dt/720;p.rot+=dt*.004}particles=particles.filter(p=>p.life>0)}
function drawTarget(q,t,w,h){const x=t.x*w,y=t.y*h,r=t.r*Math.min(w,h),glow=6+t.crack*18;q.save();q.translate(x,y);q.shadowBlur=glow;q.shadowColor='rgba(83,215,255,.65)';const g=q.createRadialGradient(-r*.28,-r*.34,r*.08,0,0,r);g.addColorStop(0,'rgba(238,252,255,.95)');g.addColorStop(.46,'rgba(112,220,245,.68)');g.addColorStop(1,'rgba(31,102,134,.40)');q.fillStyle=g;q.strokeStyle='rgba(220,249,255,.9)';q.lineWidth=Math.max(1.2,w/700);q.beginPath();for(let i=0;i<8;i++){const a=i/8*Math.PI*2-Math.PI/8,rr=r*(i%2?.92:1),px=Math.cos(a)*rr,py=Math.sin(a)*rr;i?q.lineTo(px,py):q.moveTo(px,py)}q.closePath();q.fill();q.stroke();if(t.crack>.08){q.shadowBlur=0;q.strokeStyle=`rgba(255,255,255,${.25+t.crack*.7})`;q.lineWidth=1.1;const n=3+Math.floor(t.crack*5);for(let i=0;i<n;i++){const a=i/n*Math.PI*2+t.seed*.01;q.beginPath();q.moveTo(0,0);q.lineTo(Math.cos(a)*r*(.45+t.crack*.5),Math.sin(a)*r*(.45+t.crack*.5));q.stroke()}}q.restore()}
function drawGame(pred){const c=gid('gazeCanvas');if(!c)return;resizeCanvas();const q=c.getContext('2d'),w=c.width,h=c.height;q.clearRect(0,0,w,h);const vign=q.createRadialGradient(w*.5,h*.48,w*.1,w*.5,h*.5,w*.72);vign.addColorStop(0,'rgba(0,0,0,0)');vign.addColorStop(1,'rgba(0,0,0,.34)');q.fillStyle=vign;q.fillRect(0,0,w,h);for(const t of targets)drawTarget(q,t,w,h);for(const p of particles){q.save();q.globalAlpha=gc(p.life,0,1);q.translate(p.x*w,p.y*h);q.rotate(p.rot);q.fillStyle='rgba(174,237,255,.82)';const s=5+8*p.life;q.beginPath();q.moveTo(-s,-s*.4);q.lineTo(s*.9,0);q.lineTo(-s*.5,s*.7);q.closePath();q.fill();q.restore()}if(pred&&rawLast){const L=mapVideoPoint(avg(rawLast,IDS.lIris)),R=mapVideoPoint(avg(rawLast,IDS.rIris)),tx=pred.x*w,ty=pred.y*h;q.save();q.globalCompositeOperation='lighter';q.lineCap='round';for(const o of[L,R]){if(!o)continue;const g=q.createLinearGradient(o.x,o.y,tx,ty);g.addColorStop(0,'rgba(190,245,255,.95)');g.addColorStop(.5,'rgba(68,199,255,.88)');g.addColorStop(1,'rgba(120,235,255,.72)');q.strokeStyle=g;q.shadowBlur=14;q.shadowColor='rgba(58,200,255,.95)';q.lineWidth=Math.max(2.2,w/340);q.beginPath();q.moveTo(o.x,o.y);q.lineTo(tx,ty);q.stroke()}q.shadowBlur=20;q.fillStyle='rgba(180,247,255,.92)';q.beginPath();q.arc(tx,ty,Math.max(5,w/110),0,Math.PI*2);q.fill();q.restore()}}
async function loop(t){raf=requestAnimationFrame(loop);const v=gid('gazeVideo');if(busy||!task||!v?.videoWidth||t-lastDetect<70)return;busy=true;lastDetect=t;try{const inf=gid('gazeInfer'),k=Math.min(1,inferMax/Math.max(v.videoWidth,v.videoHeight));inf.width=Math.max(1,Math.round(v.videoWidth*k));inf.height=Math.max(1,Math.round(v.videoHeight*k));inf.getContext('2d').drawImage(v,0,0,inf.width,inf.height);sampleLight(inf,t);const ts=performance.now(),r=task.detect(inf),cost=performance.now()-ts,raw=r.faceLandmarks?.[0];perfSamples.push(cost);if(perfSamples.length>=8){const a=perfSamples.reduce((s,x)=>s+x,0)/perfSamples.length;if(a>125&&inferMax>780)inferMax-=80;else if(a>95&&inferMax>860)inferMax-=50;else if(a<58&&inferMax<980)inferMax+=30;perfSamples=[]}if(!raw?.length){if(!missSince)missSince=t;status(lightLevel<60?'얼굴이 잘 안 보여요. 더 밝은 곳으로 이동해 주세요.':t-missSince>1100?'얼굴과 눈이 잘 보이게 정면을 맞춰 주세요. 안경 반사가 심하면 각도를 조금 바꿔보세요.':'얼굴과 눈을 찾는 중…');return}missSince=0;rawLast=raw;featureLast=features(raw);if(!featureLast){status(lightLevel<60?'홍채가 잘 안 보여요. 밝은 곳으로 이동해 주세요.':'홍채를 찾는 중… 눈을 자연스럽게 뜨고 화면을 바라봐 주세요.');return}if(mode==='cal')updateCal(t);else if(mode==='verify')updateVerify(t);else if(mode==='game'){const env=envMessage(featureLast);if(env&&lightLevel<66)gameHint(env);else if(headAnchor&&(Math.abs(featureLast.yaw-headAnchor.yaw)>.12||Math.abs(featureLast.pitch-headAnchor.pitch)>.11))gameHint('고개를 보정할 때 위치로 조금만 맞추면 더 정확해집니다');else gameHint('물체를 잠시 바라보면 레이저로 깨집니다');const pred=predict(featureLast),dt=Math.min(80,t-gameLast||16);gameLast=t;updateGame(pred,dt,t);drawGame(pred)}}catch(e){status('시선 추적 오류 · '+(e?.message||e))}finally{busy=false}}
function back(){stop();model=null;corrModel=null;smoothed=null;const d=gid('calDot');if(d)d.style.display='block';show('launcher')}
function bind(){gid('modeFace')?.addEventListener('click',()=>show('home'));gid('modeGaze')?.addEventListener('click',()=>show('gazeIntro'));gid('faceBack')?.addEventListener('click',()=>show('launcher'));gid('gazeBack')?.addEventListener('click',back);gid('gazeCalBack')?.addEventListener('click',back);gid('gazeStart')?.addEventListener('click',()=>start().catch(e=>{stop();show('gazeIntro');status(e?.message||String(e));alert('시선 추적을 시작하지 못했습니다.\n'+(e?.message||String(e)))}));gid('gazeGameBack')?.addEventListener('click',back);gid('recalibrate')?.addEventListener('click',()=>{stop();start().catch(e=>{show('gazeIntro');status(e?.message||String(e))})});if(mode==='new')show('launcher');if(!navigator.mediaDevices?.getUserMedia){const n=gid('cameraEnvNote');if(n)n.textContent='현재 브라우저에서는 카메라 접근이 제한되어 있습니다. Chrome에서 열어주세요.'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();