(()=>{
'use strict';
const CAL_POINTS=[
 [.08,.12],[.29,.12],[.50,.12],[.71,.12],[.92,.12],
 [.08,.37],[.29,.37],[.50,.37],[.71,.37],[.92,.37],
 [.08,.63],[.29,.63],[.50,.63],[.71,.63],[.92,.63],
 [.08,.88],[.29,.88],[.50,.88],[.71,.88],[.92,.88]
];
const VERIFY_POINTS=[
 [.14,.16],[.50,.16],[.86,.16],
 [.14,.50],[.50,.50],[.86,.50],
 [.14,.84],[.50,.84],[.86,.84]
];
const IDS={lIris:[468,469,470,471,472],rIris:[473,474,475,476,477],lCorners:[33,133],rCorners:[362,263],lTop:[159,160],lBottom:[145,144],rTop:[386,385],rBottom:[374,380]};
const gid=id=>document.getElementById(id),gc=(v,a,b)=>Math.max(a,Math.min(b,v));
const median=a=>{if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y);return b[(b.length-1)>>1]};
const avg=(raw,ids)=>{let x=0,y=0,z=0,n=0;for(const id of ids){const p=raw?.[id];if(!p)continue;x+=p.x;y+=p.y;z+=p.z||0;n++}return n?{x:x/n,y:y/n,z:z/n}:null};
const dot2=(a,b)=>a.x*b.x+a.y*b.y;
let stream=null,raf=0,busy=false,lastDetect=0,mode='idle',inferMax=980,perfSamples=[];
let calIndex=0,phaseStarted=0,pointSamples=[],calSamples=[],calProtos=[],headAnchor=null,headRef={yaw:0,pitch:0,scale:.4};
let verifyIndex=0,verifySamples=[],verifyFrames=[],model=null,flipOutputX=false,corrRows=[];
let smoothed=null,predHistory=[],rawLast=null,featureLast=null,missSince=0,lastLightCheck=0,lightLevel=100,contrastLevel=30;
let targets=[],particles=[],score=0,lastSpawn=0,gameLast=0;

function eyeGeom(raw,corners,tops,bottoms,irisIds){
 const iris=avg(raw,irisIds),a=raw?.[corners[0]],b=raw?.[corners[1]],top=avg(raw,tops),bottom=avg(raw,bottoms);if(!iris||!a||!b||!top||!bottom)return null;
 const dx=b.x-a.x,dy=b.y-a.y,len=Math.max(1e-5,Math.hypot(dx,dy)),ex={x:dx/len,y:dy/len},ey={x:-dy/len,y:dx/len},c={x:(a.x+b.x)/2,y:(a.y+b.y)/2};
 const rel=p=>({x:p.x-c.x,y:p.y-c.y}),ir=rel(iris),tr=rel(top),br=rel(bottom),iv=dot2(ir,ey),tv=dot2(tr,ey),bv=dot2(br,ey),v0=Math.min(tv,bv),vh=Math.max(1e-5,Math.abs(bv-tv));
 return{h:.5+dot2(ir,ex)/len,v:(iv-v0)/vh,open:vh/len,iris,span:len}
}
function features(raw){
 if(!raw||raw.length<478)return null;const L=eyeGeom(raw,IDS.lCorners,IDS.lTop,IDS.lBottom,IDS.lIris),R=eyeGeom(raw,IDS.rCorners,IDS.rTop,IDS.rBottom,IDS.rIris);if(!L||!R)return null;
 const le=raw[234],re=raw[454],n=raw[1],f=raw[10],c=raw[152];if(!le||!re||!n||!f||!c)return null;const fw=Math.max(1e-5,Math.hypot(re.x-le.x,re.y-le.y)),yaw=(n.x-(le.x+re.x)/2)/fw,pitch=(n.y-f.y)/Math.max(1e-5,c.y-f.y);
 return{lh:L.h,lv:L.v,rh:R.h,rv:R.v,h:(L.h+R.h)/2,v:(L.v+R.v)/2,dh:L.h-R.h,dv:L.v-R.v,yaw,pitch,l:L.iris,r:R.iris,openL:L.open,openR:R.open,faceWidth:fw}
}
function basisBoth(f){const y=f.yaw-headRef.yaw,p=f.pitch-headRef.pitch,s=(f.faceWidth-headRef.scale)/Math.max(.08,headRef.scale);return[1,f.lh,f.lv,f.rh,f.rv,f.h,f.v,f.dh,f.dv,f.h*f.v,f.lh*f.lv,f.rh*f.rv,f.h*f.h,f.v*f.v,y,p,y*f.h,p*f.v,s]}
function basisEye(f,left){const h=left?f.lh:f.rh,v=left?f.lv:f.rv,y=f.yaw-headRef.yaw,p=f.pitch-headRef.pitch,s=(f.faceWidth-headRef.scale)/Math.max(.08,headRef.scale);return[1,h,v,h*h,v*v,h*v,y,p,y*h,p*v,s]}
function solve(A,b){const n=b.length,M=A.map((r,i)=>r.slice().concat(b[i]));for(let i=0;i<n;i++){let p=i;for(let r=i+1;r<n;r++)if(Math.abs(M[r][i])>Math.abs(M[p][i]))p=r;if(Math.abs(M[p][i])<1e-10)return null;[M[i],M[p]]=[M[p],M[i]];const d=M[i][i];for(let c=i;c<=n;c++)M[i][c]/=d;for(let r=0;r<n;r++){if(r===i)continue;const k=M[r][i];if(!k)continue;for(let c=i;c<=n;c++)M[r][c]-=k*M[i][c]}}return M.map(r=>r[n])}
function fitAxis(samples,key,basis,lambda=.035){const n=basis(samples[0].f).length,A=Array.from({length:n},()=>Array(n).fill(0)),b=Array(n).fill(0);for(const s of samples){const x=basis(s.f),y=s[key];for(let i=0;i<n;i++){b[i]+=x[i]*y;for(let j=0;j<n;j++)A[i][j]+=x[i]*x[j]}}for(let i=1;i<n;i++)A[i][i]+=lambda;return solve(A,b)}
const dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0);
function percentile(a,p){if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),i=Math.min(b.length-1,Math.max(0,Math.floor((b.length-1)*p)));return b[i]}
function predictModel(m,f){if(!m)return null;const x=dot(m.bx,m.basis(f)),y=dot(m.by,m.basis(f));return{x:gc(x,-.15,1.15),y:gc(y,-.15,1.15)}}
function protoVector(f){return[f.lh,f.lv,f.rh,f.rv,f.dh,f.dv,(f.yaw-headRef.yaw)*.7,(f.pitch-headRef.pitch)*.7]}
function buildProtoScale(){const vs=calProtos.map(p=>protoVector(p.f));if(!vs.length)return Array(8).fill(1);return vs[0].map((_,i)=>Math.max(.018,percentile(vs.map(v=>v[i]),.90)-percentile(vs.map(v=>v[i]),.10)))}
function protoMedian(frames,target){const keys=['lh','lv','rh','rv','dh','dv','yaw','pitch','openL','openR','faceWidth'],f={};for(const k of keys)f[k]=median(frames.map(x=>x[k]));return{f,target}}
function predictKNN(f){if(!model?.protoScale||calProtos.length<4)return null;const v=protoVector(f),rows=calProtos.map(p=>{const q=protoVector(p.f);let d=0;for(let i=0;i<v.length;i++){const z=(v[i]-q[i])/model.protoScale[i];d+=z*z}return{p,d:Math.sqrt(d)}}).sort((a,b)=>a.d-b.d).slice(0,5);let sx=0,sy=0,sw=0;for(const r of rows){const w=1/Math.pow(.20+r.d,2);sx+=r.p.target[0]*w;sy+=r.p.target[1]*w;sw+=w}return{x:sx/sw,y:sy/sw,nearest:rows[0].d}}
function fitModel(){
 if(calSamples.length<110||calProtos.length<16)throw Error('보정 데이터가 부족합니다.');headRef={yaw:median(calSamples.map(s=>s.f.yaw)),pitch:median(calSamples.map(s=>s.f.pitch)),scale:median(calSamples.map(s=>s.f.faceWidth))};
 const bb=f=>basisBoth(f),bl=f=>basisEye(f,true),br=f=>basisEye(f,false);
 let both={bx:fitAxis(calSamples,'x',bb),by:fitAxis(calSamples,'y',bb),basis:bb},left={bx:fitAxis(calSamples,'x',bl,.045),by:fitAxis(calSamples,'y',bl,.045),basis:bl},right={bx:fitAxis(calSamples,'x',br,.045),by:fitAxis(calSamples,'y',br,.045),basis:br};
 if(!both.bx||!both.by||!left.bx||!left.by||!right.bx||!right.by)throw Error('시선 보정식을 계산하지 못했습니다.');
 const errs=calSamples.map(s=>{const p=predictModel(both,s.f);return Math.hypot(p.x-s.x,p.y-s.y)}),cut=Math.max(.05,percentile(errs,.84)),good=calSamples.filter((s,i)=>errs[i]<=cut);
 if(good.length>=90){const B={bx:fitAxis(good,'x',bb),by:fitAxis(good,'y',bb),basis:bb},L={bx:fitAxis(good,'x',bl,.045),by:fitAxis(good,'y',bl,.045),basis:bl},R={bx:fitAxis(good,'x',br,.045),by:fitAxis(good,'y',br,.045),basis:br};if(B.bx&&B.by)both=B;if(L.bx&&L.by)left=L;if(R.bx&&R.by)right=R}
 model={both,left,right,weights:{both:.30,left:.20,right:.20,knn:.30},protoScale:null,trainError:median(errs)};model.protoScale=buildProtoScale();return model
}
function rawParts(f){if(!model)return null;return{both:predictModel(model.both,f),left:predictModel(model.left,f),right:predictModel(model.right,f),knn:predictKNN(f)}}
function combineParts(parts){if(!parts)return null;let sx=0,sy=0,sw=0;for(const k of ['both','left','right','knn']){const p=parts[k],w=model.weights[k]||0;if(!p||!Number.isFinite(p.x)||!Number.isFinite(p.y)||w<=0)continue;sx+=p.x*w;sy+=p.y*w;sw+=w}return sw?{x:sx/sw,y:sy/sw}:null}
function predictRaw(f){return combineParts(rawParts(f))}
function orient(p){return flipOutputX?{x:1-p.x,y:p.y}:p}
function applyLocalCorrection(p){if(!corrRows.length)return p;const rows=corrRows.map(r=>({r,d:Math.hypot(p.x-r.p.x,p.y-r.p.y)})).sort((a,b)=>a.d-b.d).slice(0,4);let dx=0,dy=0,sw=0;for(const x of rows){const w=1/Math.pow(.05+x.d,2);dx+=x.r.dx*w;dy+=x.r.dy*w;sw+=w}const gain=gc(1-(rows[0]?.d||0)*1.6,.28,1);return{x:gc(p.x+gc(dx/sw,-.16,.16)*gain,0,1),y:gc(p.y+gc(dy/sw,-.16,.16)*gain,0,1)}}
function predict(f){let p=predictRaw(f);if(!p)return null;p=applyLocalCorrection(orient(p));predHistory.push(p);if(predHistory.length>3)predHistory.shift();const med={x:median(predHistory.map(v=>v.x)),y:median(predHistory.map(v=>v.y))};if(!smoothed){smoothed=med;return med}const d=Math.hypot(med.x-smoothed.x,med.y-smoothed.y),alpha=gc(.20+d*2.4,.20,.68);smoothed={x:smoothed.x*(1-alpha)+med.x*alpha,y:smoothed.y*(1-alpha)+med.y*alpha};return smoothed}
function status(s){const a=gid('gazeStatus'),b=gid('calStatus');if(a)a.textContent=s;if(b)b.textContent=s}
function gameHint(s){const e=document.querySelector('#gazeGame .gameHint');if(e)e.textContent=s}
function resizeCanvas(){const c=gid('gazeCanvas');if(!c)return;const r=c.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1),w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(c.width!==w||c.height!==h){c.width=w;c.height=h}}
function mapVideoPoint(p){const v=gid('gazeVideo'),c=gid('gazeCanvas');if(!p||!v||!c||!v.videoWidth||!v.videoHeight)return null;const cw=c.width,ch=c.height,sw=v.videoWidth,sh=v.videoHeight,k=Math.max(cw/sw,ch/sh),rw=sw*k,rh=sh*k,ox=(cw-rw)/2,oy=(ch-rh)/2;return{x:cw-(ox+p.x*sw*k),y:oy+p.y*sh*k}}
function attachStage(game){const v=gid('gazeVideo'),c=gid('gazeCanvas'),host=game?document.querySelector('#gazeGame .gameStage'):document.querySelector('#gazeCal .gazeStage');if(!v||!c||!host)return;host.insertBefore(v,host.firstChild);host.insertBefore(c,v.nextSibling)}
function stop(){cancelAnimationFrame(raf);raf=0;busy=false;mode='idle';if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}const v=gid('gazeVideo');if(v)v.srcObject=null}
async function start(){stop();attachStage(false);mode='loading';show('gazeCal');status('카메라 준비 중…');if(!navigator.mediaDevices?.getUserMedia)throw Error('카메라 접근이 제한되어 있습니다. Chrome에서 열어주세요.');const mp=loadTask();stream=await openCamera();const v=gid('gazeVideo');v.srcObject=stream;await v.play();status('홍채 모델 준비 중…');await mp;calIndex=0;pointSamples=[];calSamples=[];calProtos=[];verifyIndex=0;verifySamples=[];verifyFrames=[];model=null;corrRows=[];flipOutputX=false;smoothed=null;predHistory=[];headAnchor=null;missSince=0;inferMax=980;perfSamples=[];const d=gid('calDot');if(d)d.style.display='block';mode='cal';prepareCal();lastDetect=0;raf=requestAnimationFrame(loop)}
function prepareCal(){const p=CAL_POINTS[calIndex],d=gid('calDot'),prog=gid('calProgress');if(!p||!d)return;d.style.display='block';d.style.left=p[0]*100+'%';d.style.top=p[1]*100+'%';d.classList.remove('capture');void d.offsetWidth;d.classList.add('capture');if(prog)prog.textContent=`정밀 보정 ${calIndex+1} / ${CAL_POINTS.length}`;phaseStarted=performance.now();pointSamples=[]}
function prepareVerify(){const p=VERIFY_POINTS[verifyIndex],d=gid('calDot'),prog=gid('calProgress');if(!p||!d)return;d.style.display='block';d.style.left=p[0]*100+'%';d.style.top=p[1]*100+'%';d.classList.remove('capture');void d.offsetWidth;d.classList.add('capture');if(prog)prog.textContent=`정확도 확인 ${verifyIndex+1} / ${VERIFY_POINTS.length}`;phaseStarted=performance.now();verifySamples=[]}
function envMessage(f){if(lightLevel<48)return'환경이 너무 어두워요. 얼굴 앞쪽이 밝은 곳으로 이동해 주세요.';if(contrastLevel<14)return'얼굴이 흐리게 보여요. 더 밝은 곳에서 카메라를 닦고 다시 맞춰 주세요.';if(lightLevel<68)return'조금 어두워요. 얼굴 앞쪽을 밝게 하면 정확도가 좋아집니다.';if(f?.faceWidth<.23)return'얼굴이 조금 멀어요. 휴대폰을 조금 더 가까이 해주세요.';if(f?.faceWidth>.72)return'얼굴이 너무 가까워요. 휴대폰을 조금 멀리 해주세요.';if(f&&Math.min(f.openL,f.openR)<.10)return'눈을 자연스럽게 뜨고 점을 바라봐 주세요.';return null}
function headStable(f){if(!headAnchor){headAnchor={yaw:f.yaw,pitch:f.pitch};return true}return Math.abs(f.yaw-headAnchor.yaw)<.085&&Math.abs(f.pitch-headAnchor.pitch)<.075}
function robustPointFrames(frames){if(frames.length<7)return[];const keys=['lh','lv','rh','rv','yaw','pitch'],m=Object.fromEntries(keys.map(k=>[k,median(frames.map(f=>f[k]))]));return frames.filter(f=>Math.abs(f.yaw-m.yaw)<.034&&Math.abs(f.pitch-m.pitch)<.032&&Math.abs(f.lh-m.lh)<.075&&Math.abs(f.rh-m.rh)<.075&&Math.abs(f.lv-m.lv)<.11&&Math.abs(f.rv-m.rv)<.11&&Math.min(f.openL,f.openR)>.10).slice(-14)}
function updateCal(now){if(mode!=='cal'||!featureLast)return;const env=envMessage(featureLast);if(env){status(env);return}if(!headStable(featureLast)){status('고개가 움직였어요. 휴대폰과 고개를 보정 시작 위치로 맞춰 주세요.');return}const age=now-phaseStarted;if(age<300){status('점만 눈으로 따라보세요 · 고개는 고정');return}if(age<980){pointSamples.push({...featureLast});status('정밀 측정 중… 눈동자만 움직여 주세요');return}const good=robustPointFrames(pointSamples);if(good.length<7){phaseStarted=now-300;pointSamples=[];status('측정이 흔들렸어요. 같은 점을 다시 바라봐 주세요.');return}const t=CAL_POINTS[calIndex];for(const f of good)calSamples.push({f,x:t[0],y:t[1]});calProtos.push(protoMedian(good,t));calIndex++;if(calIndex>=CAL_POINTS.length){try{fitModel();mode='verify';verifyIndex=0;prepareVerify()}catch(e){status(e.message);calIndex=0;calSamples=[];calProtos=[];prepareCal()}return}prepareCal()}
function updateVerify(now){if(mode!=='verify'||!featureLast)return;const env=envMessage(featureLast);if(env){status(env);return}if(!headStable(featureLast)){status('정확도 확인 중입니다. 고개를 보정 시작 위치로 맞춰 주세요.');return}const age=now-phaseStarted;if(age<280){status('정확도 확인 중 · 점만 바라보세요');return}if(age<850){verifySamples.push({...featureLast});status('검증 측정 중…');return}const good=robustPointFrames(verifySamples);if(good.length<6){phaseStarted=now-280;verifySamples=[];return}const t=VERIFY_POINTS[verifyIndex];verifyFrames.push({target:t,frames:good});verifyIndex++;if(verifyIndex<VERIFY_POINTS.length){prepareVerify();return}finishVerify()}
function medPred(frames,kind){const ps=frames.map(f=>{const parts=rawParts(f);return kind==='combined'?combineParts(parts):parts?.[kind]}).filter(Boolean);return ps.length?{x:median(ps.map(p=>p.x)),y:median(ps.map(p=>p.y))}:null}
function corr(a,b){const mx=median(a),my=median(b);let n=0,dx=0,dy=0;for(let i=0;i<a.length;i++){const x=a[i]-mx,y=b[i]-my;n+=x*y;dx+=x*x;dy+=y*y}return n/Math.sqrt(Math.max(1e-9,dx*dy))}
function componentError(kind,flip=false){let e=0,n=0;for(const r of verifyFrames){const p=medPred(r.frames,kind);if(!p)continue;const x=flip?1-p.x:p.x;e+=Math.hypot(x-r.target[0],p.y-r.target[1]);n++}return n?e/n:1}
function finishVerify(){
 const baseRows=verifyFrames.map(r=>({target:r.target,p:medPred(r.frames,'combined')})).filter(r=>r.p),normal=baseRows.reduce((s,r)=>s+Math.hypot(r.p.x-r.target[0],r.p.y-r.target[1]),0)/baseRows.length,flipped=baseRows.reduce((s,r)=>s+Math.hypot(1-r.p.x-r.target[0],r.p.y-r.target[1]),0)/baseRows.length,cN=corr(baseRows.map(r=>r.p.x),baseRows.map(r=>r.target[0])),cF=corr(baseRows.map(r=>1-r.p.x),baseRows.map(r=>r.target[0]));
 flipOutputX=(flipped+.07<normal&&cF>cN+.15);
 const errs={both:componentError('both',flipOutputX),left:componentError('left',flipOutputX),right:componentError('right',flipOutputX),knn:componentError('knn',flipOutputX)};let sw=0;for(const k of Object.keys(errs)){model.weights[k]=1/Math.pow(.035+errs[k],2);sw+=model.weights[k]}for(const k of Object.keys(model.weights))model.weights[k]/=sw;
 const rows=[];for(const r of verifyFrames){const ps=r.frames.map(predictRaw).filter(Boolean),p={x:median(ps.map(v=>v.x)),y:median(ps.map(v=>v.y))},q=orient(p);rows.push({p:q,dx:r.target[0]-q.x,dy:r.target[1]-q.y,target:r.target})}corrRows=rows;
 const after=rows.reduce((s,r)=>{const p=applyLocalCorrection(r.p);return s+Math.hypot(p.x-r.target[0],p.y-r.target[1])},0)/rows.length,pct=Math.round(after*100),d=gid('calDot');if(d)d.style.display='none';
 if(after>.16)status(`보정 오차 약 ${pct}% · 정확도가 아직 낮습니다. 더 밝은 곳에서 휴대폰을 고정하고 다시 보정해 주세요.`);else status(`정밀 보정 완료 · 검증 오차 약 ${pct}% · 양쪽 눈 개별 모델 + 구역별 보정 적용`);
 mode='game';score=0;targets=[];particles=[];lastSpawn=0;gameLast=performance.now();smoothed=null;predHistory=[];const s=gid('gazeScore');if(s)s.textContent='0';attachStage(true);show('gazeGame');gameHint(`시선 오차 약 ${pct}% · 물체를 바라보면 레이저로 깨집니다`);setTimeout(resizeCanvas,0)
}
function sampleLight(inf,now){if(now-lastLightCheck<650)return;lastLightCheck=now;try{const ctx=inf.getContext('2d',{willReadFrequently:true}),w=inf.width,h=inf.height,step=Math.max(5,Math.floor(Math.min(w,h)/26)),data=ctx.getImageData(0,0,w,h).data;let sum=0,sum2=0,n=0;for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){const i=(y*w+x)*4,l=data[i]*.2126+data[i+1]*.7152+data[i+2]*.0722;sum+=l;sum2+=l*l;n++}if(n){lightLevel=sum/n;contrastLevel=Math.sqrt(Math.max(0,sum2/n-lightLevel*lightLevel))}}catch{}}
function spawn(now){const c=gid('gazeCanvas');if(!c||targets.length>=6||now-lastSpawn<850)return;lastSpawn=now;const m=.11,x=m+Math.random()*(1-m*2),y=.18+Math.random()*.68,r=.045+Math.random()*.025;targets.push({x,y,r,heat:0,crack:0,seed:Math.random()*9999})}
function shatter(t){score+=100;const s=gid('gazeScore');if(s)s.textContent=String(score);for(let i=0;i<18;i++){const a=Math.random()*Math.PI*2,sp=.18+Math.random()*.38;particles.push({x:t.x,y:t.y,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp-.08,life:1,rot:Math.random()*6})}}
function updateGame(pred,dt,now){spawn(now);let hit=null;if(pred)for(const t of targets){if(Math.hypot(pred.x-t.x,pred.y-t.y)<t.r*1.08){hit=t;break}}for(const t of targets){if(t===hit){t.heat+=dt;t.crack=gc(t.heat/560,0,1)}else t.heat=Math.max(0,t.heat-dt*.36)}const dead=targets.filter(t=>t.heat>=560);for(const t of dead)shatter(t);targets=targets.filter(t=>t.heat<560);for(const p of particles){p.x+=p.vx*dt/1000;p.y+=p.vy*dt/1000;p.vy+=.32*dt/1000;p.life-=dt/720;p.rot+=dt*.004}particles=particles.filter(p=>p.life>0)}
function drawTarget(q,t,w,h){const x=t.x*w,y=t.y*h,r=t.r*Math.min(w,h),glow=6+t.crack*18;q.save();q.translate(x,y);q.shadowBlur=glow;q.shadowColor='rgba(83,215,255,.65)';const g=q.createRadialGradient(-r*.28,-r*.34,r*.08,0,0,r);g.addColorStop(0,'rgba(238,252,255,.95)');g.addColorStop(.46,'rgba(112,220,245,.68)');g.addColorStop(1,'rgba(31,102,134,.40)');q.fillStyle=g;q.strokeStyle='rgba(220,249,255,.9)';q.lineWidth=Math.max(1.2,w/700);q.beginPath();for(let i=0;i<8;i++){const a=i/8*Math.PI*2-Math.PI/8,rr=r*(i%2?.92:1),px=Math.cos(a)*rr,py=Math.sin(a)*rr;i?q.lineTo(px,py):q.moveTo(px,py)}q.closePath();q.fill();q.stroke();if(t.crack>.08){q.shadowBlur=0;q.strokeStyle=`rgba(255,255,255,${.25+t.crack*.7})`;q.lineWidth=1.1;const n=3+Math.floor(t.crack*5);for(let i=0;i<n;i++){const a=i/n*Math.PI*2+t.seed*.01;q.beginPath();q.moveTo(0,0);q.lineTo(Math.cos(a)*r*(.45+t.crack*.5),Math.sin(a)*r*(.45+t.crack*.5));q.stroke()}}q.restore()}
function drawGame(pred){const c=gid('gazeCanvas');if(!c)return;resizeCanvas();const q=c.getContext('2d'),w=c.width,h=c.height;q.clearRect(0,0,w,h);const vign=q.createRadialGradient(w*.5,h*.48,w*.1,w*.5,h*.5,w*.72);vign.addColorStop(0,'rgba(0,0,0,0)');vign.addColorStop(1,'rgba(0,0,0,.34)');q.fillStyle=vign;q.fillRect(0,0,w,h);for(const t of targets)drawTarget(q,t,w,h);for(const p of particles){q.save();q.globalAlpha=gc(p.life,0,1);q.translate(p.x*w,p.y*h);q.rotate(p.rot);q.fillStyle='rgba(174,237,255,.82)';const s=5+8*p.life;q.beginPath();q.moveTo(-s,-s*.4);q.lineTo(s*.9,0);q.lineTo(-s*.5,s*.7);q.closePath();q.fill();q.restore()}if(pred&&rawLast){const L=mapVideoPoint(avg(rawLast,IDS.lIris)),R=mapVideoPoint(avg(rawLast,IDS.rIris)),tx=pred.x*w,ty=pred.y*h;q.save();q.globalCompositeOperation='lighter';q.lineCap='round';for(const o of[L,R]){if(!o)continue;const g=q.createLinearGradient(o.x,o.y,tx,ty);g.addColorStop(0,'rgba(190,245,255,.95)');g.addColorStop(.5,'rgba(68,199,255,.88)');g.addColorStop(1,'rgba(120,235,255,.72)');q.strokeStyle=g;q.shadowBlur=14;q.shadowColor='rgba(58,200,255,.95)';q.lineWidth=Math.max(2.2,w/340);q.beginPath();q.moveTo(o.x,o.y);q.lineTo(tx,ty);q.stroke()}q.shadowBlur=20;q.fillStyle='rgba(180,247,255,.92)';q.beginPath();q.arc(tx,ty,Math.max(5,w/110),0,Math.PI*2);q.fill();q.restore()}}
async function loop(t){raf=requestAnimationFrame(loop);const v=gid('gazeVideo');if(busy||!task||!v?.videoWidth||t-lastDetect<66)return;busy=true;lastDetect=t;try{const inf=gid('gazeInfer'),k=Math.min(1,inferMax/Math.max(v.videoWidth,v.videoHeight));inf.width=Math.max(1,Math.round(v.videoWidth*k));inf.height=Math.max(1,Math.round(v.videoHeight*k));inf.getContext('2d').drawImage(v,0,0,inf.width,inf.height);sampleLight(inf,t);const ts=performance.now(),r=task.detect(inf),cost=performance.now()-ts,raw=r.faceLandmarks?.[0];perfSamples.push(cost);if(perfSamples.length>=8){const a=perfSamples.reduce((s,x)=>s+x,0)/perfSamples.length;if(a>125&&inferMax>800)inferMax-=80;else if(a>95&&inferMax>880)inferMax-=50;else if(a<55&&inferMax<1020)inferMax+=30;perfSamples=[]}if(!raw?.length){if(!missSince)missSince=t;status(lightLevel<62?'얼굴이 잘 안 보여요. 더 밝은 곳으로 이동해 주세요.':t-missSince>1100?'얼굴과 눈이 잘 보이게 정면을 맞춰 주세요. 안경 반사가 심하면 각도를 조금 바꿔보세요.':'얼굴과 눈을 찾는 중…');return}missSince=0;rawLast=raw;featureLast=features(raw);if(!featureLast){status(lightLevel<62?'홍채가 잘 안 보여요. 밝은 곳으로 이동해 주세요.':'홍채를 찾는 중… 눈을 자연스럽게 뜨고 화면을 바라봐 주세요.');return}if(mode==='cal')updateCal(t);else if(mode==='verify')updateVerify(t);else if(mode==='game'){const env=envMessage(featureLast);if(env&&lightLevel<68)gameHint(env);else if(headAnchor&&(Math.abs(featureLast.yaw-headAnchor.yaw)>.10||Math.abs(featureLast.pitch-headAnchor.pitch)>.09))gameHint('고개를 보정할 때 위치로 맞추면 정확도가 좋아집니다');const pred=predict(featureLast),dt=Math.min(80,t-gameLast||16);gameLast=t;updateGame(pred,dt,t);drawGame(pred)}}catch(e){status('시선 추적 오류 · '+(e?.message||e))}finally{busy=false}}
function back(){stop();model=null;corrRows=[];smoothed=null;const d=gid('calDot');if(d)d.style.display='block';show('launcher')}
function bind(){gid('modeFace')?.addEventListener('click',()=>show('home'));gid('modeGaze')?.addEventListener('click',()=>show('gazeIntro'));gid('faceBack')?.addEventListener('click',()=>show('launcher'));gid('gazeBack')?.addEventListener('click',back);gid('gazeCalBack')?.addEventListener('click',back);gid('gazeStart')?.addEventListener('click',()=>start().catch(e=>{stop();show('gazeIntro');status(e?.message||String(e));alert('시선 추적을 시작하지 못했습니다.\n'+(e?.message||String(e)))}));gid('gazeGameBack')?.addEventListener('click',back);gid('recalibrate')?.addEventListener('click',()=>{stop();start().catch(e=>{show('gazeIntro');status(e?.message||String(e))})});if(mode==='new')show('launcher');if(!navigator.mediaDevices?.getUserMedia){const n=gid('cameraEnvNote');if(n)n.textContent='현재 브라우저에서는 카메라 접근이 제한되어 있습니다. Chrome에서 열어주세요.'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();