const OVAL=[10,338,297,332,284,251,389,356,454,323,361,288,397,365,379,378,400,377,152,148,176,149,150,136,172,58,132,93,234,127,162,21,54,103,67,109];
const LEYE=[33,7,163,144,145,153,154,155,133,173,157,158,159,160,161,246],REYE=[362,382,381,380,374,373,390,249,263,466,388,387,386,385,384,398],MOUTH=[61,146,91,181,84,17,314,405,321,375,291,308,324,318,402,317,14,87,178,88,95,78];
const BROW_L=[70,63,105,66,107,55,65],BROW_R=[336,296,334,293,300,276,283];
let TRI_CACHE=null,EDGE_CACHE=null;
function bounds(mesh){const xs=OVAL.map(i=>mesh[i]?.[0]).filter(Number.isFinite),ys=OVAL.map(i=>mesh[i]?.[1]).filter(Number.isFinite);return[Math.min(...xs),Math.max(...xs),Math.min(...ys),Math.max(...ys)]}
function mapper(mesh,w,h,pad=.12){const [x1,x2,y1,y2]=bounds(mesh),fw=x2-x1,fh=y2-y1,s=Math.min(w*(1-pad*2)/fw,h*(1-pad*2)/fh),cx=(x1+x2)/2,cy=(y1+y2)/2;return p=>[w/2+(p[0]-cx)*s,h/2+(p[1]-cy)*s]}
function pathPoly(q,mesh,ids,mp){q.beginPath();let started=false;for(const id of ids){const p=mesh[id];if(!p)continue;const [x,y]=mp(p);started?q.lineTo(x,y):q.moveTo(x,y);started=true}q.closePath()}
function circleData(a,b,c){const ax=a.x,ay=a.y,bx=b.x,by=b.y,cx=c.x,cy=c.y,d=2*(ax*(by-cy)+bx*(cy-ay)+cx*(ay-by));if(Math.abs(d)<1e-10)return{x:0,y:0,r2:Infinity};const aa=ax*ax+ay*ay,bb=bx*bx+by*by,cc=cx*cx+cy*cy,x=(aa*(by-cy)+bb*(cy-ay)+cc*(ay-by))/d,y=(aa*(cx-bx)+bb*(ax-cx)+cc*(bx-ax))/d;return{x,y,r2:(x-ax)*(x-ax)+(y-ay)*(y-ay)}}
function buildTriangles(mesh){
  if(TRI_CACHE)return TRI_CACHE;const pts=mesh.slice(0,468).map((p,i)=>({x:p[0],y:p[1],i}));let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const p of pts){minX=Math.min(minX,p.x);minY=Math.min(minY,p.y);maxX=Math.max(maxX,p.x);maxY=Math.max(maxY,p.y)}const d=Math.max(maxX-minX,maxY-minY)||1,cx=(minX+maxX)/2,cy=(minY+maxY)/2,n=pts.length,all=pts.concat([{x:cx-20*d,y:cy+12*d,i:n},{x:cx,y:cy-20*d,i:n+1},{x:cx+20*d,y:cy+12*d,i:n+2}]);let tris=[[n,n+1,n+2]];
  for(let pi=0;pi<n;pi++){
    const p=all[pi],bad=[];for(let ti=0;ti<tris.length;ti++){const t=tris[ti],cc=circleData(all[t[0]],all[t[1]],all[t[2]]);if((p.x-cc.x)*(p.x-cc.x)+(p.y-cc.y)*(p.y-cc.y)<=cc.r2+1e-9)bad.push(ti)}
    const edgeCount=new Map();for(const bi of bad){const t=tris[bi];for(const e of [[t[0],t[1]],[t[1],t[2]],[t[2],t[0]]]){const a=Math.min(e[0],e[1]),b=Math.max(e[0],e[1]),k=a+','+b;edgeCount.set(k,(edgeCount.get(k)||0)+1)}}const dead=new Set(bad);tris=tris.filter((_,i)=>!dead.has(i));for(const [k,c] of edgeCount)if(c===1){const [a,b]=k.split(',').map(Number);tris.push([a,b,pi])}
  }
  TRI_CACHE=tris.filter(t=>t[0]<n&&t[1]<n&&t[2]<n);const es=new Set();for(const t of TRI_CACHE)for(const [a,b] of [[t[0],t[1]],[t[1],t[2]],[t[2],t[0]]])es.add(Math.min(a,b)+','+Math.max(a,b));EDGE_CACHE=[...es].map(x=>x.split(',').map(Number));return TRI_CACHE
}
function depthRange(mesh){let lo=Infinity,hi=-Infinity;for(let i=0;i<468;i++){const z=mesh[i]?.[2];if(!Number.isFinite(z))continue;lo=Math.min(lo,z);hi=Math.max(hi,z)}return Number.isFinite(lo)?[lo,hi]:[-1,1]}
function normalLight(a,b,c){const ux=b[0]-a[0],uy=b[1]-a[1],uz=b[2]-a[2],vx=c[0]-a[0],vy=c[1]-a[1],vz=c[2]-a[2];let nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx,l=Math.hypot(nx,ny,nz)||1;nx/=l;ny/=l;nz/=l;if(nz<0){nx=-nx;ny=-ny;nz=-nz}const lx=-.28,ly=-.34,lz=.90,ll=Math.hypot(lx,ly,lz),dot=clamp((nx*lx+ny*ly+nz*lz)/ll,0,1);return dot}
function skinColor(light,depth){const lum=clamp(.72+light*.24+depth*.055,.64,1.04),r=Math.round(218*lum),g=Math.round(169*lum),b=Math.round(148*lum);return`rgb(${clamp(r,0,255)},${clamp(g,0,255)},${clamp(b,0,255)})`}
function drawDepthSurface(q,mesh,mp){
  const tris=buildTriangles(mesh),[z0,z1]=depthRange(mesh),zr=(z1-z0)||1,sorted=[...tris].sort((u,v)=>((mesh[u[0]][2]+mesh[u[1]][2]+mesh[u[2]][2])-(mesh[v[0]][2]+mesh[v[1]][2]+mesh[v[2]][2]))));q.save();pathPoly(q,mesh,OVAL,mp);q.clip();
  for(const t of sorted){const a=mesh[t[0]],b=mesh[t[1]],c=mesh[t[2]],A=mp(a),B=mp(b),C=mp(c),depth=(((a[2]+b[2]+c[2])/3)-z0)/zr,fill=skinColor(normalLight(a,b,c),depth);q.beginPath();q.moveTo(A[0],A[1]);q.lineTo(B[0],B[1]);q.lineTo(C[0],C[1]);q.closePath();q.fillStyle=fill;q.fill();q.strokeStyle=fill;q.lineWidth=.7;q.stroke()}
  const glow=q.createRadialGradient(q.canvas.width*.43,q.canvas.height*.29,12,q.canvas.width*.45,q.canvas.height*.40,q.canvas.width*.48);glow.addColorStop(0,'rgba(255,245,235,.22)');glow.addColorStop(.48,'rgba(255,255,255,.035)');glow.addColorStop(1,'rgba(70,34,28,.14)');q.fillStyle=glow;q.fillRect(0,0,q.canvas.width,q.canvas.height);q.restore()
}
function drawWire(canvas,mesh,color='#73c9ff'){
  if(!mesh)return;const r=canvas.getBoundingClientRect(),d=Math.min(2.25,devicePixelRatio||1),w=Math.max(220,Math.round(r.width*d)),h=Math.max(250,Math.round((r.height||r.width*1.1)*d));canvas.width=w;canvas.height=h;const q=canvas.getContext('2d'),bg=q.createRadialGradient(w*.5,h*.42,10,w*.5,h*.5,w*.7);bg.addColorStop(0,'#171b21');bg.addColorStop(1,'#08090b');q.fillStyle=bg;q.fillRect(0,0,w,h);const mp=mapper(mesh,w,h,.115),[z0,z1]=depthRange(mesh),zr=(z1-z0)||1;buildTriangles(mesh);
  pathPoly(q,mesh,OVAL,mp);const fill=q.createRadialGradient(w*.47,h*.38,8,w*.5,h*.5,w*.42);fill.addColorStop(0,'rgba(255,255,255,.055)');fill.addColorStop(1,'rgba(255,255,255,.012)');q.fillStyle=fill;q.fill();
  q.lineCap='round';for(const [a,b] of EDGE_CACHE||[]){const p=mesh[a],r2=mesh[b];if(!p||!r2)continue;const A=mp(p),B=mp(r2),zn=(((p[2]+r2[2])*.5)-z0)/zr;q.strokeStyle=`rgba(126,205,255,${.10+zn*.22})`;q.lineWidth=Math.max(.55,w/1150+(zn*.35));q.beginPath();q.moveTo(A[0],A[1]);q.lineTo(B[0],B[1]);q.stroke()}
  q.globalCompositeOperation='lighter';q.strokeStyle=color;q.globalAlpha=.78;q.lineWidth=Math.max(1.15,w/620);for(const wire of WIRES){q.beginPath();wire.forEach((id,j)=>{const p=mesh[id];if(!p)return;const [x,y]=mp(p);j?q.lineTo(x,y):q.moveTo(x,y)});q.stroke()}q.globalAlpha=1;q.globalCompositeOperation='source-over';
  q.fillStyle='rgba(235,249,255,.8)';for(const id of [10,152,1,33,133,362,263,61,291]){const p=mesh[id];if(!p)continue;const [x,y]=mp(p);q.beginPath();q.arc(x,y,Math.max(1.15,w/520),0,Math.PI*2);q.fill()}
}
function eyeShape(q,mesh,ids,irisIds,mp){
  const pts=ids.map(i=>mesh[i]).filter(Boolean);if(!pts.length)return;pathPoly(q,mesh,ids,mp);const eg=q.createLinearGradient(0,mp(mesh[ids[0]])[1]-12,0,mp(mesh[ids[Math.floor(ids.length/2)]])[1]+12);eg.addColorStop(0,'#fbfaf8');eg.addColorStop(1,'#ded8d3');q.fillStyle=eg;q.fill();q.strokeStyle='rgba(63,43,39,.42)';q.lineWidth=2;q.stroke();const iris=irisIds.map(i=>mesh[i]).filter(Boolean);if(!iris.length)return;const cx=iris.reduce((s,p)=>s+mp(p)[0],0)/iris.length,cy=iris.reduce((s,p)=>s+mp(p)[1],0)/iris.length,rad=Math.max(5,iris.reduce((s,p)=>s+Math.hypot(mp(p)[0]-cx,mp(p)[1]-cy),0)/iris.length*1.36),ig=q.createRadialGradient(cx-rad*.22,cy-rad*.27,rad*.12,cx,cy,rad);ig.addColorStop(0,'#87958e');ig.addColorStop(.48,'#5d7168');ig.addColorStop(1,'#29352f');q.fillStyle=ig;q.beginPath();q.arc(cx,cy,rad,0,Math.PI*2);q.fill();q.fillStyle='#121815';q.beginPath();q.arc(cx,cy,rad*.46,0,Math.PI*2);q.fill();q.fillStyle='rgba(255,255,255,.86)';q.beginPath();q.arc(cx-rad*.28,cy-rad*.32,rad*.16,0,Math.PI*2);q.fill();q.strokeStyle='rgba(50,34,31,.28)';q.lineWidth=1.2;q.beginPath();q.arc(cx,cy,rad,0,Math.PI*2);q.stroke()
}
function renderSynthetic(mesh){
  const c=$('synthetic'),q=c.getContext('2d'),w=c.width,h=c.height,mp=mapper(mesh,w,h,.105);q.clearRect(0,0,w,h);const bg=q.createLinearGradient(0,0,0,h);bg.addColorStop(0,'#f0ede8');bg.addColorStop(1,'#d8d2c8');q.fillStyle=bg;q.fillRect(0,0,w,h);
  q.save();q.filter='blur(18px)';q.fillStyle='rgba(59,42,36,.22)';pathPoly(q,mesh,OVAL,mp);q.translate(0,14);q.fill();q.restore();drawDepthSurface(q,mesh,mp);
  q.strokeStyle='rgba(77,48,42,.24)';q.lineWidth=2.1;pathPoly(q,mesh,OVAL,mp);q.stroke();eyeShape(q,mesh,LEYE,[468,469,470,471,472],mp);eyeShape(q,mesh,REYE,[473,474,475,476,477],mp);
  const n1=mp(mesh[1]),nL=mp(mesh[98]),nR=mp(mesh[327]),nTop=mp(mesh[168]),noseW=Math.max(12,Math.abs(nR[0]-nL[0]));q.save();q.filter='blur(7px)';const ng=q.createLinearGradient(nL[0],0,nR[0],0);ng.addColorStop(0,'rgba(93,51,42,.22)');ng.addColorStop(.45,'rgba(255,247,239,.16)');ng.addColorStop(.56,'rgba(255,251,245,.25)');ng.addColorStop(1,'rgba(76,40,34,.23)');q.strokeStyle=ng;q.lineWidth=noseW*.32;q.lineCap='round';q.beginPath();q.moveTo(nTop[0],nTop[1]+5);q.quadraticCurveTo(n1[0]-2,(nTop[1]+n1[1])*.53,n1[0],n1[1]);q.stroke();q.restore();q.fillStyle='rgba(75,40,35,.30)';for(const p of [nL,nR]){q.beginPath();q.ellipse(p[0],p[1]+2,4.8,2.1,0,0,Math.PI*2);q.fill()}
  pathPoly(q,mesh,MOUTH,mp);const lip=q.createLinearGradient(0,mp(mesh[13])[1]-9,0,mp(mesh[14])[1]+12);lip.addColorStop(0,'#aa686a');lip.addColorStop(.52,'#98595e');lip.addColorStop(1,'#854c53');q.fillStyle=lip;q.fill();q.strokeStyle='rgba(73,35,40,.28)';q.lineWidth=1.25;q.stroke();const m13=mp(mesh[13]),m14=mp(mesh[14]);q.strokeStyle='rgba(72,34,39,.34)';q.lineWidth=1.1;q.beginPath();q.moveTo(mp(mesh[78])[0],(m13[1]+m14[1])*.5);q.quadraticCurveTo((m13[0]+m14[0])*.5,(m13[1]+m14[1])*.5+1,mp(mesh[308])[0],(m13[1]+m14[1])*.5);q.stroke();
  q.strokeStyle='rgba(65,45,39,.58)';q.lineWidth=5;q.lineCap='round';for(const ids of [BROW_L,BROW_R]){q.beginPath();ids.forEach((id,j)=>{const p=mp(mesh[id]);j?q.lineTo(...p):q.moveTo(...p)});q.stroke()}
  q.save();q.filter='blur(10px)';q.fillStyle='rgba(255,248,239,.13)';for(const id of [205,425]){const p=mp(mesh[id]);q.beginPath();q.ellipse(p[0],p[1],40,18,0,0,Math.PI*2);q.fill()}q.restore();q.fillStyle='rgba(255,255,255,.12)';q.beginPath();q.ellipse(w*.42,h*.32,34,70,-.18,0,Math.PI*2);q.fill()
}
function mixMesh(a,b,t){const x=t/100;return a.map((p,i)=>[p[0]*(1-x)+b[i][0]*x,p[1]*(1-x)+b[i][1]*x,p[2]*(1-x)+b[i][2]*x])}
function renderResult(j){
  resultData=j;const r=j.result,a=j.creator.canonical,b=j.guest.canonical;$('score').textContent=r.overall.toFixed(1);$('scoreLabel').textContent=r.label;const names={faceShape:'얼굴형',eyes:'눈',nose:'코',mouth:'입',jaw:'턱',symmetry:'대칭'};$('bars').innerHTML=Object.entries(r.parts).map(([k,v])=>`<div class="barRow"><span>${names[k]||k}</span><div class="bar"><i style="width:${v}%"></i></div><b>${v}</b></div>`).join('');let qn=$('qualityNote');if(!qn){qn=document.createElement('div');qn.id='qualityNote';qn.className='qualityNote';$('scoreLabel').after(qn)}const qa=j.creator?.fusion?.quality,qb=j.guest?.fusion?.quality;qn.textContent=Number.isFinite(qa)&&Number.isFinite(qb)?`측정 품질 A ${qa}% · B ${qb}% · 478점 다각도 융합`: '478점 다각도 얼굴 구조 비교';show('result');drawWire($('meshA'),a,'#77bdf8');drawWire($('meshB'),b,'#f4a7ba');let mixRaf=0;const update=()=>{mixRaf=0;const t=+$('mix').value,m=(t===50&&r.mergedMesh)?r.mergedMesh:mixMesh(a,b,t);$('mixA').textContent='A '+(100-t)+'%';$('mixB').textContent='B '+t+'%';drawWire($('meshM'),m,'#70dfa9');renderSynthetic(m)};$('mix').oninput=()=>{if(!mixRaf)mixRaf=requestAnimationFrame(update)};$('mix').value=50;update()
}
async function renderActions(){const a=$('actions');a.innerHTML='';if(mode==='guest'){const b=document.createElement('button');b.className='btn primary';b.textContent='메쉬 비교 전송 중…';b.disabled=true;a.appendChild(b);try{const j=await api({action:'join',id:sessionId,token:sessionToken,guest:captured},25000);renderResult(j)}catch(e){b.disabled=false;b.textContent='비교 다시 시도';b.onclick=()=>renderActions();fail(e)}return}const b=document.createElement('button');b.className='btn primary';b.textContent='친구와 얼굴 구조 비교하기';b.onclick=createInvite;a.appendChild(b);const r=document.createElement('button');r.className='btn';r.textContent='다시 스캔';r.onclick=startCamera;a.appendChild(r)}
async function createInvite(){try{const j=await api({action:'create',creator:captured},25000);sessionId=j.id;sessionToken=j.ownerToken;localStorage.setItem('fd_owner:'+j.id,j.ownerToken);history.replaceState(null,'','#owner='+j.id);const link=CANON+'?join='+encodeURIComponent(j.id+'.'+j.inviteToken);$('inviteLink').value=link;show('wait');pollOwner()}catch(e){fail(e)}}
function pollOwner(){clearInterval(pollTimer);const go=async()=>{try{const j=await api({action:'get',id:sessionId,token:sessionToken});if(j.status==='complete'){clearInterval(pollTimer);renderResult(j)}}catch(e){log('POLL '+e.message)}};go();pollTimer=setInterval(go,2500)}
$('copy').onclick=async()=>{await navigator.clipboard.writeText($('inviteLink').value);$('copy').textContent='복사됨';setTimeout(()=>$('copy').textContent='복사',1200)};
$('shareInvite').onclick=()=>navigator.share?navigator.share({title:'얼굴 구조 비교',text:'우리 얼굴 구조가 얼마나 닮았는지 비교해보자',url:$('inviteLink').value}).catch(()=>{}):$('copy').click();
$('again').onclick=()=>{history.replaceState(null,'',location.pathname);mode='new';sessionId=sessionToken=null;captured=null;show('home')};$('cancel').onclick=()=>{stopCamera();show('home')};$('start').onclick=()=>startCamera().catch(e=>{stopCamera();show('home');fail(e)});
async function init(){buildUI();const s=launchState();mode=s.mode;if(mode==='guest'){sessionId=s.id;sessionToken=s.token;$('invite').classList.add('on');try{const j=await api({action:'get',id:sessionId,token:sessionToken});if(j.status==='complete'){renderResult(j);return}}catch(e){fail(e);mode='new';sessionStorage.removeItem('fd_guest_v4')}}else if(mode==='owner'){sessionId=s.id;sessionToken=s.token;try{const j=await api({action:'get',id:sessionId,token:sessionToken});if(j.status==='complete'){renderResult(j);return}$('inviteLink').value='';show('wait');$('wait').querySelector('.linkRow').style.display='none';$('shareInvite').style.display='none';pollOwner();return}catch{mode='new'}}show('home');loadTask().catch(e=>log(e.message))}init();