function buildUI(){const g=$('segments');g.innerHTML='';for(let i=0;i<N;i++){const a=i/N*Math.PI*2,x1=50+44*Math.cos(a-.062),y1=70+63*Math.sin(a-.062),x2=50+44*Math.cos(a+.062),y2=70+63*Math.sin(a+.062),p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',`M${x1} ${y1} L${x2} ${y2}`);p.classList.add('seg');g.appendChild(p)}$('chips').innerHTML=LABELS.map(x=>`<span class="chip">${x}</span>`).join('')}
function coverMap(sw,sh,dw,dh){const k=Math.max(dw/sw,dh/sh),rw=sw*k,rh=sh*k,ox=(dw-rw)/2,oy=(dh-rh)/2;return p=>({x:dw-(ox+p.x*sw*k),y:oy+p.y*sh*k})}
const WIRES=[[10,338,297,332,284,251,389,356,454,323,361,288,397,365,379,378,400,377,152,148,176,149,150,136,172,58,132,93,234,127,162,21,54,103,67,109,10],[33,7,163,144,145,153,154,155,133,173,157,158,159,160,161,246,33],[362,382,381,380,374,373,390,249,263,466,388,387,386,385,384,398,362],[61,146,91,181,84,17,314,405,321,375,291,308,324,318,402,317,14,87,178,88,95,78,61],[168,6,197,195,5,4,1,2,98],[168,6,197,195,5,4,1,2,327]];
function drawLive(raw){const c=$('overlay'),r=c.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1),w=Math.round(r.width*d),h=Math.round(r.height*d);if(c.width!==w||c.height!==h){c.width=w;c.height=h}const q=c.getContext('2d');q.clearRect(0,0,w,h);if(!raw?.length)return;const mp=coverMap($('video').videoWidth,$('video').videoHeight,w,h),P=raw.map(mp);q.strokeStyle='rgba(115,201,255,.64)';q.lineWidth=Math.max(1,w/620);for(const wire of WIRES){q.beginPath();for(let j=0;j<wire.length;j++){const p=P[wire[j]];if(!p)continue;j?q.lineTo(p.x,p.y):q.moveTo(p.x,p.y)}q.stroke()}if(vision?.FaceLandmarker?.FACE_LANDMARKS_TESSELATION){q.globalAlpha=.28;q.beginPath();for(const e of vision.FaceLandmarker.FACE_LANDMARKS_TESSELATION){const a=P[e.start],b=P[e.end];if(!a||!b)continue;q.moveTo(a.x,a.y);q.lineTo(b.x,b.y)}q.stroke();q.globalAlpha=1}}
function canonical(raw){const sw=$('video').videoWidth,sh=$('video').videoHeight;if(!sw||!sh)return null;const p=raw.map(v=>[v.x*sw,v.y*sh,(v.z||0)*sw]);const L=[33,133].map(i=>p[i]),R=[362,263].map(i=>p[i]),lc=[(L[0][0]+L[1][0])/2,(L[0][1]+L[1][1])/2],rc=[(R[0][0]+R[1][0])/2,(R[0][1]+R[1][1])/2],cx=(lc[0]+rc[0])/2,cy=(lc[1]+rc[1])/2,dx=rc[0]-lc[0],dy=rc[1]-lc[1],s=Math.hypot(dx,dy);if(!s)return null;const ca=dx/s,sa=dy/s;return p.map(v=>{const x=v[0]-cx,y=v[1]-cy;return[(x*ca+y*sa)/s,(-x*sa+y*ca)/s,v[2]/s]})}
function pose(raw){const sw=$('video').videoWidth,sh=$('video').videoHeight,p=i=>[raw[i].x*sw,raw[i].y*sh],L=p(234),R=p(454),N=p(1),F=p(10),C=p(152),fw=Math.hypot(R[0]-L[0],R[1]-L[1])||1,cx=(L[0]+R[0])/2,yaw=(N[0]-cx)/fw,pitch=(N[1]-F[1])/((C[1]-F[1])||1);return{yaw,pitch}}
function feature(m){const d=(a,b)=>dist(m[a],m[b]);return[d(234,454),d(10,152),d(172,397),d(33,133),d(362,263),d(133,362),d(98,327),d(61,291),d(1,152),d(10,1),d(13,14),d(6,152)]}
function shapeSig(m){const d=(a,b)=>dist(m[a],m[b]);return[[234,454],[10,152],[172,397],[33,263],[133,362],[98,327],[61,291],[1,152],[10,1],[6,152],[58,288],[93,323],[132,361],[148,377]].map(x=>d(x[0],x[1]))}
function medianMesh(frames){if(!frames.length)return null;const n=frames[0].mesh.length,out=[];for(let i=0;i<n;i++)out.push([med(frames.map(f=>f.mesh[i][0])),med(frames.map(f=>f.mesh[i][1])),med(frames.map(f=>f.mesh[i][2]))]);return out}
function medianVec(frames){if(!frames.length)return Array(12).fill(0);const n=frames[0].feat.length;return Array.from({length:n},(_,i)=>med(frames.map(f=>f.feat[i])))}
function bucketName(yaw,dy){if(Math.abs(yaw)<.05&&Math.abs(dy)<.045)return'center';if(yaw>.105)return'right';if(yaw<-.105)return'left';if(dy<-.07)return'up';if(dy>.07)return'down';return null}
function bucketCounts(){const o={center:centerFrames.length,right:0,left:0,up:0,down:0};for(const f of orbitFrames)if(f.bucket)o[f.bucket]++;return o}
function updateProgress(){const counts=bucketCounts(),coverage=bins.filter(n=>n>=2).length,ring=Math.min(1,coverage/21),bp=KEYS.reduce((s,k)=>s+Math.min(1,counts[k]/REQ[k]),0)/5,p=Math.min(99,Math.floor((ring*.76+bp*.24)*100)),done=coverage>=21&&KEYS.every(k=>counts[k]>=REQ[k]);$('percent').textContent=(done?100:p)+'%';document.querySelectorAll('.seg').forEach((e,i)=>e.classList.toggle('done',bins[i]>=2));document.querySelectorAll('.chip').forEach((e,i)=>e.classList.toggle('done',counts[KEYS[i]]>=REQ[KEYS[i]]));if(done)finishScan();else if(p>72){const miss=KEYS.find(k=>counts[k]<REQ[k]);const t={center:'정면을 잠시 더',right:'오른쪽으로 조금 더',left:'왼쪽으로 조금 더',up:'고개를 조금 더 위로',down:'고개를 조금 더 아래로'};$('hint').textContent=t[miss]||'원을 따라 천천히 움직이세요'}}
function resetScan(){phaseName='front';basePitch=null;hold=0;lastLoop=performance.now();centerFrames=[];orbitFrames=[];bins=Array(N).fill(0);bestFront=null;captured=null;busy=false;$('percent').textContent='0%';$('phase').textContent='정면 보정';$('capTitle').textContent='정면을 바라봐 주세요';$('hint').textContent='얼굴을 가운데 맞추고 잠시 유지하세요';buildUI()}
function stopCamera(){cancelAnimationFrame(raf);raf=0;stream?.getTracks().forEach(t=>t.stop());stream=null;$('video').srcObject=null}
async function startCamera(){resetScan();show('camera');const modelP=loadTask();stream=await openCamera();$('video').srcObject=stream;await $('video').play();$('modelState').textContent='카메라 켜짐 · 모델 준비 중';await modelP;$('modelState').textContent='얼굴 모델 준비 완료';lastDetect=0;raf=requestAnimationFrame(loop)}
async function loop(t){raf=requestAnimationFrame(loop);if(!task||busy||$('video').readyState<2||t-lastDetect<90)return;busy=true;lastDetect=t;try{const v=$('video'),inf=$('infer'),max=760,k=Math.min(1,max/Math.max(v.videoWidth,v.videoHeight));inf.width=Math.max(1,Math.round(v.videoWidth*k));inf.height=Math.max(1,Math.round(v.videoHeight*k));inf.getContext('2d').drawImage(v,0,0,inf.width,inf.height);const ts=performance.now(),r=task.detect(inf),raw=r.faceLandmarks?.[0];$('perf').textContent=Math.round(performance.now()-ts)+'ms';if(!raw?.length){$('hint').textContent='얼굴을 화면 안에 맞춰 주세요';return}drawLive(raw);const m=canonical(raw),po=pose(raw);if(!m)return;const fr={mesh:m,feat:feature(m),pose:po};if(phaseName==='front'){const frontOK=Math.abs(po.yaw)<.065;if(frontOK){const dt=Math.min(140,t-lastLoop);hold+=dt;centerFrames.push(fr);if(!bestFront||Math.abs(po.yaw)<Math.abs(bestFront.pose.yaw))bestFront=fr;$('percent').textContent=Math.min(20,Math.floor(hold/550*20))+'%';if(hold>=550&&centerFrames.length>=REQ.center){basePitch=med(centerFrames.map(x=>x.pose.pitch));phaseName='orbit';$('phase').textContent='다각도 mesh 수집';$('capTitle').textContent='고개를 천천히 움직여 주세요';$('hint').textContent='원을 따라 좌·우·위·아래를 자연스럽게 훑어주세요'}}else{hold=Math.max(0,hold-80);$('hint').textContent='정면을 바라봐 주세요'}}else if(phaseName==='orbit'){const dy=po.pitch-basePitch,x=clamp(-po.yaw/.16,-1.25,1.25),y=clamp(dy/.09,-1.25,1.25),rad=Math.hypot(x,y);if(rad>.38&&rad<1.35){const a=(Math.atan2(y,x)+Math.PI*2)%(Math.PI*2),bin=Math.round(a/(Math.PI*2)*N)%N;bins[bin]++;const bucket=bucketName(po.yaw,dy);orbitFrames.push({...fr,bucket});if(orbitFrames.length>240)orbitFrames.shift()}updateProgress()}lastLoop=t}catch(e){log('DETECT '+(e?.message||e));$('modelState').textContent='DETECT 오류'}finally{busy=false}}
function makePayload(){const cm=medianMesh(centerFrames);if(!cm)throw Error('정면 mesh가 부족합니다.');const groups={center:centerFrames,right:orbitFrames.filter(f=>f.bucket==='right'),left:orbitFrames.filter(f=>f.bucket==='left'),up:orbitFrames.filter(f=>f.bucket==='up'),down:orbitFrames.filter(f=>f.bucket==='down')};const views={};for(const k of KEYS)views[k]=medianVec(groups[k]);return{version:4,canonical:cm,features:feature(cm),views,shape:shapeSig(cm),coverage:bins.filter(n=>n>=2).length,capturedAt:new Date().toISOString()}}
let finishing=false;async function finishScan(){if(finishing||phaseName==='done')return;finishing=true;phaseName='done';$('percent').textContent='100%';$('phase').textContent='완료';$('capTitle').textContent='Mesh 수집 완료';try{captured=makePayload();stopCamera();drawWire($('myMesh'),captured.canonical,'#73c9ff');$('captureInfo').textContent=`${captured.canonical.length} points · coverage ${captured.coverage}/24 · 사진 저장 없음`;show('me');renderActions()}catch(e){fail(e);phaseName='orbit'}finally{finishing=false}}